### ISSUE TITLE
Didnt trace the spring bean

### ISSUE THREAD

**Issue by satan1999** [evernat/grails-melody-plugin#21]
Hi There

I put @net.bull.javamelody.MonitoredWithSpring into one of my helper class ( initialized by spring in resource.groovy ) and one controller class

But i didn't see any trace of them in Statistics spring.

Just wondering if i did the right way

Cheers
Wallace

**Comment by evernat** [comment]
If you want to use @net.bull.javamelody.MonitoredWithSpring, you need to add net/bull/javamelody/monitoring-spring.xml in your Spring's context as said at https://code.google.com/p/javamelody/wiki/UserGuide#9._Business_facades_%28if_Spring%29

**Comment by evernat** [comment]
Information given and no response from the reporter so closing.
